"""
Django settings for maria project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from common.functions.find_urls import find_fe_url,find_be_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*6i&pwt90qvimj$vt5_l_p6%gb8+sn46@ocp1@y+n%%9%h+x#6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',#jazzmin For Admin Panel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oauth2_provider',# For Oauth2',
    'User',
    'silk',
    'common',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    "silk.middleware.SilkyMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
]
# AUTHENTICATION_BACKENDS = (
    
# )   

ROOT_URLCONF = 'maria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maria.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # use mysql backend (works for MariaDB too)
        'NAME': config('DB_NAME'),                   # your database name
        'USER': config('DB_USER'),                 # your MariaDB user
        'PASSWORD': config('DB_PASSWORD'),          # your MariaDB password
        'HOST': config('DB_HOST') ,                   # or "localhost"
        'PORT':config('DB_PORT') ,                        # default MariaDB port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",      # Only if you have a /static folder in your project root
]

STATIC_ROOT = BASE_DIR / "staticfiles"   # For collectstatic (prod)



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# #Sentry
# import sentry_sdk

# sentry_sdk.init(
#     dsn="https://your-sentry-dsn@o123456.ingest.sentry.io/",
#     send_default_pii=True,  # captures user IP, headers, etc.
# )


# JAZZMIN CONFIGURATION
CURRENT_INSTANCE_SOURCE = config('ENVIRONMENT_NAME', default='localhost')


name=f"MYAPP"
JAZZMIN_SETTINGS = {
    "site_brand": name,
    "site_title": name,
    "site_logo": "images/logo.png",
    "site_header": f"{name} Admin",
    "welcome_sign": f"Welcome to the {name} Admin",
    "copyright": f"{name} Ltd ",
    "show_ui_builder" :True,
    "topmenu_links": [
        {"name": "SILK LOG", "url": find_fe_url(CURRENT_INSTANCE_SOURCE), "new_window": True},
        {"name": "Backend URL", "url": find_be_url(CURRENT_INSTANCE_SOURCE), "new_window": True},
    ],
    "usermenu_links":[
        {"name":"","url":"","new_window":True}
    ]
}